In [1]:
import numpy as py

In [6]:
from numpy.random import randn

In [7]:
data={i:randn() for i in range(7)}

In [8]:
data

{0: -0.47857444415226325,
 1: 0.37787070373469084,
 2: 1.640109306611545,
 3: -0.015420784179581145,
 4: -0.9476934815079895,
 5: 0.5598207917764023,
 6: -0.9494692207840401}

In [9]:
an_apple=27

In [10]:
an_example=42

In [11]:
an

NameError: name 'an' is not defined

In [12]:
b=[1,2,3]

In [13]:
b.

SyntaxError: invalid syntax (<ipython-input-13-ca00e70340f9>, line 1)

In [14]:
import datetime

In [18]:
datetime.

SyntaxError: invalid syntax (<ipython-input-18-8a767ef9a071>, line 1)

In [20]:
book_scripts

NameError: name 'book_scripts' is not defined

In [21]:
path='book_scripts/'

In [22]:
b?

In [25]:
print(np.*load*?)

SyntaxError: invalid syntax (<ipython-input-25-0d7d6268e850>, line 1)

In [34]:
def f(x,y,z):
    return (x+y)/z
a=5
b=6
c=7.5

In [35]:
c

7.5

In [36]:
result

1.4666666666666666

In [37]:
%paste

ERROR:root:Line magic function `%paste` not found.


In [40]:
data

{0: -0.47857444415226325,
 1: 0.37787070373469084,
 2: 1.640109306611545,
 3: -0.015420784179581145,
 4: -0.9476934815079895,
 5: 0.5598207917764023,
 6: -0.9494692207840401}

In [42]:
data1=[6,7.5,8,0,1]

In [46]:
import numpy as np

In [51]:
arr1=np.array(data1)

In [52]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [53]:
data2=[[1,2,3,4],[5,6,7,8]]

In [54]:
arr2=np.array(data2)

In [55]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
arr2.ndim

2

In [57]:
arr2.shape

(2, 4)

In [58]:
arr1.dtype

dtype('float64')

In [59]:
arr2.dtype

dtype('int64')

In [60]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [61]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [62]:
np.empty((2,3,2))

array([[[ -1.49166815e-154,  -2.32035509e+077],
        [  2.96439388e-323,   4.94065646e-324],
        [  0.00000000e+000,   4.47031923e-038]],

       [[  0.00000000e+000,   2.57111314e+184],
        [  0.00000000e+000,   4.81699598e-038],
        [  0.00000000e+000,   8.34644604e-309]]])

In [64]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
arr=np.array([1,2,3,4,5])

In [66]:
arr.dtype

dtype('int64')

In [67]:
float_arr=arr.astype(np.float64)

In [68]:
float_arr.dtype

dtype('float64')

In [69]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [70]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [71]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [72]:
numeric_strings=np.array(['1.25','-9.6','42'],dtype=np.string_)

In [73]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [74]:
arr=np.array([[1.,2.,3.],[4.,5.,6.,]])

In [75]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [76]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [77]:
arr-arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [78]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [79]:
arr**0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [80]:
arr=np.arange(10)

In [81]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr[5]

5

In [83]:
arr[5:8]

array([5, 6, 7])

In [84]:
arr[5:8]=12

In [85]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [86]:
arr_slice=arr[5:8]

In [89]:
arr_slice[1]=12345

In [90]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [91]:
arr_slice[:]=64

In [92]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [93]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [94]:
arr2d[2]

array([7, 8, 9])

In [95]:
arr2d[0][2]

3

In [96]:
arr2d[0,2]

3

In [97]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [129]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [130]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [131]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
old_values=arr3d[0].copy()

In [133]:
arr3d[0]=42

In [134]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [135]:
arr3d[1,0]

array([7, 8, 9])

In [136]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [137]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [140]:
arr2d[1,:2]

array([4, 5])

In [141]:
arr2d[2,:1]

array([7])

In [142]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [143]:
arr2d[:2,1:]=0

In [144]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [8]:
import numpy as np

In [16]:
arr=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)

In [17]:
arr

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [19]:
arr=='Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [20]:
data[names=='Bob']

array([[ 0.58096777, -0.45377026, -1.79233104,  0.14222976],
       [ 0.75632849, -0.10372908, -0.38396791, -1.06263437]])

In [21]:
data[arr=='Bob',2:]

array([[-1.79233104,  0.14222976],
       [-0.38396791, -1.06263437]])

In [26]:
data[arr=='Bob',3]

array([ 0.14222976, -1.06263437])

In [27]:
names!='Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [29]:
data[~(arr=='Bob')]

array([[ 0.62422218,  0.67926204,  0.70808402, -1.47479686],
       [-0.35289349,  0.43118311,  0.27234318, -0.32009931],
       [ 1.54255002, -0.34888625, -1.64769291,  0.69109083],
       [ 0.47727858,  0.30249776, -0.02243803,  0.29277517],
       [ 0.32328346, -2.04681433, -0.91934929, -1.57172452]])

In [34]:
mask = (arr=='Bob') | (arr=='Will')

In [35]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [36]:
data[mask]

array([[ 0.58096777, -0.45377026, -1.79233104,  0.14222976],
       [-0.35289349,  0.43118311,  0.27234318, -0.32009931],
       [ 0.75632849, -0.10372908, -0.38396791, -1.06263437],
       [ 1.54255002, -0.34888625, -1.64769291,  0.69109083]])

In [37]:
#把负值设为0
data[data<0]=0

In [38]:
data

array([[ 0.58096777,  0.        ,  0.        ,  0.14222976],
       [ 0.62422218,  0.67926204,  0.70808402,  0.        ],
       [ 0.        ,  0.43118311,  0.27234318,  0.        ],
       [ 0.75632849,  0.        ,  0.        ,  0.        ],
       [ 1.54255002,  0.        ,  0.        ,  0.69109083],
       [ 0.47727858,  0.30249776,  0.        ,  0.29277517],
       [ 0.32328346,  0.        ,  0.        ,  0.        ]])

In [40]:
data[arr!='Joe']=7

In [41]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.62422218,  0.67926204,  0.70808402,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.47727858,  0.30249776,  0.        ,  0.29277517],
       [ 0.32328346,  0.        ,  0.        ,  0.        ]])

In [42]:
arr=np.empty((8,4))

In [43]:
for i in range(8):
    arr[i]=i

In [44]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [45]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [46]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [47]:
arr=np.arange(32).reshape(8,4)

In [48]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [51]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [49]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [52]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [54]:
#全1的矩阵
data=np.ones((3,4))

In [55]:
data

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [56]:
from scipy import linalg

In [57]:
arr=np.array([[1,2],[3,4]])

In [58]:
linalg.det(arr)

-2.0

In [59]:
#Matplotlib,基于Numpy，

In [61]:
from matplotlib import pyplot

In [62]:
#df[2:5] head. tail. 

In [ ]:
# 数组 ndarray（N维数组），效率比列表高，有丰富的函数
# 维度称为轴（axes），轴的个数为秩（rank）


In [64]:
import array

In [65]:
array.array('B',range(5))

array('B', [0, 1, 2, 3, 4])

In [73]:
# ndarray.ndim .shape .size .dtype .itemsize

In [69]:
data.ndim

2

In [70]:
data.size

12

In [71]:
data.itemsize # 占了8个字节，64个比特

8

In [72]:
data.dtype

dtype('float64')

In [74]:
aArray=np.array([1,2,3])

In [75]:
aArray

array([1, 2, 3])

In [79]:
bArray=np.array([(1,2,3),(4,5,6)])

In [80]:
bArray

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
bArray.ndim,bArray.shape,bArray.dtype

(2, (2, 3), dtype('int64'))

In [82]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [84]:
np.arange(1,5,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [85]:
# 等分1到2，以10为划分
np.linspace(1,2,10,endpoint=0)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9])

In [86]:
np.linspace(1,2,10,endpoint=1)

array([ 1.        ,  1.11111111,  1.22222222,  1.33333333,  1.44444444,
        1.55555556,  1.66666667,  1.77777778,  1.88888889,  2.        ])

In [87]:
np.random.random((2,2))

array([[ 0.94033572,  0.67653391],
       [ 0.3405041 ,  0.92778532]])

In [88]:
np.fromfunction(lambda i, j:(i+1)*(j+1),(9,9))

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.],
       [  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
       [  4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.],
       [  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.],
       [  6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.],
       [  7.,  14.,  21.,  28.,  35.,  42.,  49.,  56.,  63.],
       [  8.,  16.,  24.,  32.,  40.,  48.,  56.,  64.,  72.],
       [  9.,  18.,  27.,  36.,  45.,  54.,  63.,  72.,  81.]])

In [90]:
aArray=np.array([(1,2,3),(4,5,6)])

In [91]:
print(aArray[1])

[4 5 6]


In [92]:
# 冒号表示全取
print(aArray[:,[0,1]])

[[1 2]
 [4 5]]


In [93]:
print(aArray[1,[0,1]])

[4 5]


In [95]:
bArray=aArray.reshape(3,2)

In [96]:
bArray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
aArray

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
bArray=np.array([1,3,7])

In [100]:
cArray=np.array([3,5,8])

In [101]:
d=bArray*cArray

In [102]:
d

array([ 3, 15, 56])

In [108]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])

In [109]:
a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [110]:
aArray=np.array([(6,5,4),(3,2,1)])

In [111]:
aArray.sum()

21

In [112]:
aArray

array([[6, 5, 4],
       [3, 2, 1]])

In [113]:
aArray.sum(axis=0)

array([9, 7, 5])

In [115]:
aArray.sum(axis=1)

array([15,  6])

In [116]:
aArray.min()

1

In [117]:
aArray.argmin()

5

In [118]:
aArray.std()

1.707825127659933

In [119]:
aArray.var()

2.9166666666666665

In [120]:
aArray.mean()

3.5

In [121]:
# 对数组每一个函数进行操作 ufunc,universal function,add, average, 

In [122]:
import time
import math 
import numpy as np

In [123]:
x=np.arange(0,100,0.01)

In [124]:
t_m1=time.clock()

In [125]:
for i,t in enumerate(x):
    x[i]=math.pow((math.sin(t)),2)

In [126]:
q=[5,6,7,8]

In [128]:
# enumerate作用：得到元组对
for i in enumerate(q):
    print(i)

(0, 5)
(1, 6)
(2, 7)
(3, 8)


In [129]:
t_m2=time.clock()

In [130]:
y=np.arange(0,100,0.01)

In [131]:
t_n1=time.clock()

In [132]:
y=np.power(np.sin(y),2)

In [133]:
t_n2=time.clock()

In [136]:
t_n2-t_n1

0.020323999999999565

In [137]:
# dot 矩阵内积； linalg.det 行列式 linalg.inv 逆矩阵 linalg.solve 多元一次方程组求根 linalg.eig 求特征值和特征向量

In [138]:
x=np.array([[1,2],[3,4]])

In [139]:
r1=np.linalg.det(x)

In [140]:
print(r1)

-2.0


In [141]:
r2=np.linalg.inv(x)

In [142]:
print(r2)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [143]:
r3=np.dot(x,x)

In [144]:
print(r3)

[[ 7 10]
 [15 22]]


In [146]:
# 解矩阵
y=(5,7)

In [148]:
r4=np.linalg.solve(x,y)

In [149]:
r4

array([-3.,  4.])